### ISSUE TITLE
Can't make the bot Start

### ISSUE THREAD

**Issue by HighKitty** [thboss/CS2-PUGs#1]
![image](https://github.com/thboss/CS2-PUGs/assets/74864982/12f067a1-ff2b-4def-9597-82679e3c6dc0)

Also not really understanding why.

Maybe I get something mixed up here

"web": {
    "base_url": "XXX", <<---Do you mean my Domain?
    "api_key": "XXX" <<---Is that Steam API?
    
    I think from the Discord Delevoper Site I did everything correctly

**Comment by HighKitty** [comment]
{
  "bot": {
    "prefix": "!",
    "token": "xxx",
    "guild_id": xxx,
    "sync_commands_globally": true,
    "debug": false,
    "maps": {
      "competitive": {
        "de_dust2": "Dust II",
        "de_inferno": "Inferno",
        "de_vertigo": "Vertigo",
        "de_overpass": "Overpass",
        "de_mirage": "Mirage",
        "de_nuke": "Nuke",
        "de_ancient": "Ancient"
      },
      "wingman": {
        "de_boyard": "Boyard",
        "de_chalice": "Chalice",
        "de_cobblestone": "Cobblestone",
        "de_shortdust": "Shortdust",
        "de_shortnuke": "Shortnuke",
        "de_train": "Train",
        "de_vertigo": "Vertigo"
      }
    }
  },
  "web": {
    "base_url": "xxx",
    "api_key": "xxx"
  },
  "db": {
    "user": "g5",
    "password": "xxx",
    "database": "g5",
    "host": "localhost",
    "port": "5432"
  }
}

**Comment by thboss** [comment]
You might forgot to enable server members intent and server message intent on your bot developers portal.

**Comment by HighKitty** [comment]
![image](https://github.com/thboss/CS2-PUGs/assets/74864982/9bd1fef6-3fce-4dc9-bf9c-08dc62d4ccc8)
Its checked

**Comment by thboss** [comment]
Check your bot token.
